// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package dependency_inversion

// Injectors from wire.go:

// +build wireinject
func initApp() *App {
	config := NewConfig()
	datasource := NewRedis(config)
	app := NewApp(datasource)
	return app
}
