// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: promotion.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLuListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LuId         int32            `protobuf:"varint,1,opt,name=luId,proto3" json:"luId,omitempty"`
	Luname       string           `protobuf:"bytes,2,opt,name=luname,proto3" json:"luname,omitempty"`
	DayPriceList map[string]int32 `protobuf:"bytes,3,rep,name=dayPriceList,proto3" json:"dayPriceList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Tag          []string         `protobuf:"bytes,4,rep,name=tag,proto3" json:"tag,omitempty"`
}

func (x *GetLuListReq) Reset() {
	*x = GetLuListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLuListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLuListReq) ProtoMessage() {}

func (x *GetLuListReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLuListReq.ProtoReflect.Descriptor instead.
func (*GetLuListReq) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{0}
}

func (x *GetLuListReq) GetLuId() int32 {
	if x != nil {
		return x.LuId
	}
	return 0
}

func (x *GetLuListReq) GetLuname() string {
	if x != nil {
		return x.Luname
	}
	return ""
}

func (x *GetLuListReq) GetDayPriceList() map[string]int32 {
	if x != nil {
		return x.DayPriceList
	}
	return nil
}

func (x *GetLuListReq) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

type GetLuListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*LuResponse `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *GetLuListResponse) Reset() {
	*x = GetLuListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLuListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLuListResponse) ProtoMessage() {}

func (x *GetLuListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLuListResponse.ProtoReflect.Descriptor instead.
func (*GetLuListResponse) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{1}
}

func (x *GetLuListResponse) GetList() []*LuResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type LuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Luname string `protobuf:"bytes,1,opt,name=luname,proto3" json:"luname,omitempty"`
	Luid   int64  `protobuf:"varint,2,opt,name=luid,proto3" json:"luid,omitempty"`
}

func (x *LuResponse) Reset() {
	*x = LuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuResponse) ProtoMessage() {}

func (x *LuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuResponse.ProtoReflect.Descriptor instead.
func (*LuResponse) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{2}
}

func (x *LuResponse) GetLuname() string {
	if x != nil {
		return x.Luname
	}
	return ""
}

func (x *LuResponse) GetLuid() int64 {
	if x != nil {
		return x.Luid
	}
	return 0
}

var File_promotion_proto protoreflect.FileDescriptor

var file_promotion_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x4c, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x75, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x6c, 0x75, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x75, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x43,
	0x0a, 0x0c, 0x64, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x65, 0x74, 0x4c, 0x75, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x2e, 0x44, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x64, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x03, 0x74, 0x61, 0x67, 0x1a, 0x3f, 0x0a, 0x11, 0x44, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x34, 0x0a, 0x11, 0x67, 0x65, 0x74, 0x4c, 0x75, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6c, 0x75, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x0a,
	0x6c, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x75,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x75, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x6c, 0x75, 0x69, 0x64, 0x32, 0x3b, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x4c, 0x75, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x0d, 0x2e, 0x67, 0x65, 0x74, 0x4c, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x12, 0x2e, 0x67, 0x65, 0x74, 0x4c, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x47, 0x6f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_promotion_proto_rawDescOnce sync.Once
	file_promotion_proto_rawDescData = file_promotion_proto_rawDesc
)

func file_promotion_proto_rawDescGZIP() []byte {
	file_promotion_proto_rawDescOnce.Do(func() {
		file_promotion_proto_rawDescData = protoimpl.X.CompressGZIP(file_promotion_proto_rawDescData)
	})
	return file_promotion_proto_rawDescData
}

var file_promotion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_promotion_proto_goTypes = []interface{}{
	(*GetLuListReq)(nil),      // 0: getLuListReq
	(*GetLuListResponse)(nil), // 1: getLuListResponse
	(*LuResponse)(nil),        // 2: luResponse
	nil,                       // 3: getLuListReq.DayPriceListEntry
}
var file_promotion_proto_depIdxs = []int32{
	3, // 0: getLuListReq.dayPriceList:type_name -> getLuListReq.DayPriceListEntry
	2, // 1: getLuListResponse.List:type_name -> luResponse
	0, // 2: Promotion.getLuList:input_type -> getLuListReq
	1, // 3: Promotion.getLuList:output_type -> getLuListResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_promotion_proto_init() }
func file_promotion_proto_init() {
	if File_promotion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_promotion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLuListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLuListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_promotion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_promotion_proto_goTypes,
		DependencyIndexes: file_promotion_proto_depIdxs,
		MessageInfos:      file_promotion_proto_msgTypes,
	}.Build()
	File_promotion_proto = out.File
	file_promotion_proto_rawDesc = nil
	file_promotion_proto_goTypes = nil
	file_promotion_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PromotionClient is the client API for Promotion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PromotionClient interface {
	GetLuList(ctx context.Context, in *GetLuListReq, opts ...grpc.CallOption) (*GetLuListResponse, error)
}

type promotionClient struct {
	cc grpc.ClientConnInterface
}

func NewPromotionClient(cc grpc.ClientConnInterface) PromotionClient {
	return &promotionClient{cc}
}

func (c *promotionClient) GetLuList(ctx context.Context, in *GetLuListReq, opts ...grpc.CallOption) (*GetLuListResponse, error) {
	out := new(GetLuListResponse)
	err := c.cc.Invoke(ctx, "/Promotion/getLuList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionServer is the server API for Promotion service.
type PromotionServer interface {
	GetLuList(context.Context, *GetLuListReq) (*GetLuListResponse, error)
}

// UnimplementedPromotionServer can be embedded to have forward compatible implementations.
type UnimplementedPromotionServer struct {
}

func (*UnimplementedPromotionServer) GetLuList(context.Context, *GetLuListReq) (*GetLuListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLuList not implemented")
}

func RegisterPromotionServer(s *grpc.Server, srv PromotionServer) {
	s.RegisterService(&_Promotion_serviceDesc, srv)
}

func _Promotion_GetLuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLuListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).GetLuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Promotion/GetLuList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).GetLuList(ctx, req.(*GetLuListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Promotion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Promotion",
	HandlerType: (*PromotionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getLuList",
			Handler:    _Promotion_GetLuList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promotion.proto",
}
